/**
 * Type of filesystem link.
 */
export type LinkType = 'file' | 'dir' | 'junction';

/**
 * Lifecycle status of a link operation.
 */
export type LinkStatus =
  | 'created'
  | 'already_linked'
  | 'replaced'
  | 'would_create'
  | 'would_replace'
  | 'error';

/**
 * Options for creating symbolic links.
 */
export interface LinkOptions {
  readonly force?: boolean;
  readonly dryRun?: boolean;
  readonly absolute?: boolean;
  readonly allowDangling?: boolean;
  readonly cwd?: string;
  readonly verbose?: boolean;
}

/**
 * Structured outcome of a link operation.
 */
export interface LinkResult {
  readonly status: LinkStatus;
  readonly source: string;
  readonly target: string;
  readonly linkValue: string;
  readonly type: LinkType;
  readonly message?: string;
}

/**
 * Options for unlinking operations.
 */
export interface UnlinkOptions {
  readonly dryRun?: boolean;
  readonly cwd?: string;
  readonly verbose?: boolean;
}

/**
 * Structured outcome of an unlink operation.
 */
export interface UnlinkResult {
  readonly target: string;
  readonly removed: boolean;
  readonly wasLink: boolean;
  readonly message?: string;
}

/**
 * Diagnostic status of an inspected path.
 */
export type InspectStatus =
  | 'valid'
  | 'broken'
  | 'regular_file'
  | 'regular_dir'
  | 'not_found';

/**
 * Structured diagnostic information for an inspected path.
 */
export interface InspectResult {
  readonly path: string;
  readonly exists: boolean;
  readonly isSymlink: boolean;
  readonly linkType?: LinkType;
  readonly linkValue?: string;
  readonly resolvedSource?: string;
  readonly sourceExists?: boolean;
  readonly status: InspectStatus;
  readonly message?: string;
}

/**
 * Target configuration for an AI agent's instructions.
 */
export interface InstructionTarget {
  readonly target: string;
  readonly nativeAgentsMd: boolean;
}

/**
 * Target configuration for an AI agent's skill directory.
 */
export interface SkillTarget {
  readonly target: string;
  readonly nativeSkillsDir?: boolean;
}

/**
 * Target configuration for an AI agent's rules directory.
 */
export interface RuleTarget {
  readonly target: string;
}

/**
 * Agent registry descriptor defining paths and compatibility for a specific AI agent tool.
 */
export interface AgentPreset {
  readonly id: string;
  readonly name: string;
  readonly instructions?: InstructionTarget;
  readonly skills?: SkillTarget;
  readonly rules?: RuleTarget;
}

/**
 * Diagnostic health check item for doctor command.
 */
export interface DoctorCheckItem {
  readonly title: string;
  readonly status: 'pass' | 'warn' | 'fail';
  readonly details: string;
}

/**
 * Diagnostic report generated by doctor command.
 */
export interface DoctorReport {
  readonly checks: readonly DoctorCheckItem[];
  readonly allPassed: boolean;
}
